greeks = {
    "Alp": "α",
    "Bet": "β",
    "Gam": "γ",
    "Del": "δ",
    "Eps": "ε",
    "Zet": "ζ",
    "Eta": "η",
    "The": "θ",
    "Iot": "ι",
    "Kap": "κ",
    "Lam": "λ",
    "Mu": "μ",
    "Nu": "ν",
    "Xi": "ξ",
    "Omi": "ο",
    "Pi": "π",
    "Rho": "ρ",
    "Sig": "σ",
    "Tau": "τ",
    "Ups": "υ",
    "Phi": "φ",
    "Chi": "χ",
    "Psi": "ψ",
    "Ome": "ω",
}

orderedgreek = [
    "Alpha",
    "Beta",
    "Gamma",
    "Delta",
    "Epsilon",
    "Zeta",
    "Eta",
    "Theta",
    "Iota",
    "Kappa",
    "Lambda",
    "Mu",
    "Nu",
    "Xi",
    "Omicron",
    "Pi",
    "Rho",
    "Sigma",
    "Tau",
    "Upsilon",
    "Phi",
    "Chi",
    "Psi",
    "Omega",
]

constellations = {
    "And": ("Andromeda", "Andromedae"),
    "Ant": ("Antlia", "Antliae"),
    "Aps": ("Apus", "Apodis"),
    "Aqr": ("Aquarius", "Aquarii"),
    "Aql": ("Aquila", "Aquilae"),
    "Ara": ("Ara", "Arae"),
    "Ari": ("Aries", "Arietis"),
    "Aur": ("Auriga", "Aurigae"),
    "Boo": ("Bootes", "Bootis"),
    "Cae": ("Caelum", "Caeli"),
    "Cam": ("Camelopardalis", "Camelopardalis"),
    "Cnc": ("Cancer", "Cancri"),
    "CVn": ("Canes Venatici", "Canum Venaticorum"),
    "CMa": ("Canis Major", "Canis Majoris"),
    "CMi": ("Canis Minor", "Canis Minoris"),
    "Cap": ("Capricornus", "Capricorni"),
    "Car": ("Carina", "Carinae"),
    "Cas": ("Cassiopeia", "Cassiopeiae"),
    "Cen": ("Centaurus", "Centauri"),
    "Cep": ("Cepheus", "Cephei"),
    "Cet": ("Cetus", "Ceti"),
    "Cha": ("Chamaeleon", "Chamaeleontis"),
    "Cir": ("Circinus", "Circini"),
    "Col": ("Columba", "Columbae"),
    "Com": ("Coma Berenices", "Comae Berenices"),
    "CrA": ("Corona Australis", "Coronae Australis"),
    "CrB": ("Corona Borealis", "Coronae Borealis"),
    "Crv": ("Corvus", "Corvi"),
    "Crt": ("Crater", "Crateris"),
    "Cru": ("Crux", "Crucis"),
    "Cyg": ("Cygnus", "Cygni"),
    "Del": ("Delphinus", "Delphini"),
    "Dor": ("Dorado", "Doradus"),
    "Dra": ("Draco", "Draconis"),
    "Equ": ("Equuleus", "Equulei"),
    "Eri": ("Eridanus", "Eridani"),
    "For": ("Fornax", "Fornacis"),
    "Gem": ("Gemini", "Geminorum"),
    "Gru": ("Grus", "Gruis"),
    "Her": ("Hercules", "Herculis"),
    "Hor": ("Horologium", "Horologii"),
    "Hya": ("Hydra", "Hydrae"),
    "Hyi": ("Hydrus", "Hydri"),
    "Ind": ("Indus", "Indi"),
    "Lac": ("Lacerta", "Lacertae"),
    "Leo": ("Leo", "Leonis"),
    "LMi": ("Leo Minor", "Leonis Minoris"),
    "Lep": ("Lepus", "Leporis"),
    "Lib": ("Libra", "Librae"),
    "Lup": ("Lupus", "Lupi"),
    "Lyn": ("Lynx", "Lyncis"),
    "Lyr": ("Lyra", "Lyrae"),
    "Men": ("Mensa", "Mensae"),
    "Mic": ("Microscopium", "Microscopii"),
    "Mon": ("Monoceros", "Monocerotis"),
    "Mus": ("Musca", "Muscae"),
    "Nor": ("Norma", "Normae"),
    "Oct": ("Octans", "Octantis"),
    "Oph": ("Ophiuchus", "Ophiuchi"),
    "Ori": ("Orion", "Orionis"),
    "Pav": ("Pavo", "Pavonis"),
    "Peg": ("Pegasus", "Pegasi"),
    "Per": ("Perseus", "Persei"),
    "Phe": ("Phoenix", "Phoenicis"),
    "Pic": ("Pictor", "Pictoris"),
    "Psc": ("Pisces", "Piscium"),
    "PsA": ("Piscis Austrinus", "Piscis Austrini"),
    "Pup": ("Puppis", "Puppis"),
    "Pyx": ("Pyxis", "Pyxidis"),
    "Ret": ("Reticulum", "Reticuli"),
    "Sge": ("Sagitta", "Sagittae"),
    "Sgr": ("Sagittarius", "Sagittarii"),
    "Sco": ("Scorpius", "Scorpii"),
    "Scl": ("Sculptor", "Sculptoris"),
    "Sct": ("Scutum", "Scuti"),
    "Ser": ("Serpens", "Serpentis"),
    "Sex": ("Sextans", "Sextantis"),
    "Tau": ("Taurus", "Tauri"),
    "Tel": ("Telescopium", "Telescopii"),
    "Tri": ("Triangulum", "Trianguli"),
    "TrA": ("Triangulum Australe", "Trianguli Australis"),
    "Tuc": ("Tucana", "Tucanae"),
    "UMa": ("Ursa Major", "Ursae Majoris"),
    "UMi": ("Ursa Minor", "Ursae Minoris"),
    "Vel": ("Vela", "Velorum"),
    "Vir": ("Virgo", "Virginis"),
    "Vol": ("Volans", "Volantis"),
    "Vul": ("Vulpecula", "Vulpeculae"),
}

starnames = {
    "And": {
        "Alp": "Alpheratz",
        "Bet": "Mirach",
        "Gam": "Almach",
        "Xi": "Adhil",
        "Ups": "Titawin",
    },
    "Ant": {},
    "Aps": {},
    "Aqr": {
        "Alp": "Sadalmelik",
        "Bet": "Sadalsuud",
        "Gam": "Sadachbia",
        "Del": "Skat",
        "Eps": "Albali",
        "The": "Ancha",
        "Kap": "Situla",
        "Xi": "Bunda",
    },
    "Aql": {
        "Alp": "Altair",
        "Bet": "Alshain",
        "Gam": "Tarazed",
        "Zet": "Okab",
        "Xi": "Libertas",
    },
    "Ara": {
        "Alp": "Choo",
        "Mu": "Cervantes",
    },
    "Ari": {
        "Alp": "Hamal",
        "Bet": "Sheratan",
        "Gam": "Mesarthim",
        "Del": "Botein",
    },
    "Aur": {
        "Alp": "Capella",
        "Bet": "Menkalinan",
        "Gam": "Elnath",
        "Eps": "Almaaz",
        "Zet": "Saclateni",
        "Eta": "Haedus",
        "The": "Mahasim",
        "Iot": "Hassaleh",
    },
    "Boo": {
        "Alp": "Arcturus",
        "Bet": "Nekkar",
        "Gam": "Seginus",
        "Del": "Princeps",
        "Eps": "Izar",
        "Eta": "Muphird",
        "Lam": "Xuange",
        "Mu": "Alkarulops",
    },
    "Cae": {},
    "Cam": {},
    "Cnc": {
        "Alp": "Acubens",
        "Bet": "Tarf",
        "Gam": "Asellus Borealis",
        "Del": "Asellus Australis",
        "Eps": "Meleph",
        "Zet": "Tegmine",
        "Lam": "Piautos",
        "Xi": "Nahn",
    },
    "CVn": {
        "Alp": "Cor Caroli",
        "Bet": "Chara",
    },
    "CMa": {
        "Alp": "Sirius",
        "Bet": "Mirzam",
        "Gam": "Muliphein",
        "Del": "Wezen",
        "Eps": "Adhara",
        "Zet": "Furud",
        "Eta": "Aludra",
        "Sig": "Unurgunite",
    },
    "CMi": {
        "Alp": "Procyon",
        "Bet": "Gomeisa",
    },
    "Cap": {
        "Alp": "Algedi",
        "Bet": "Dabih",
        "Gam": "Nashira",
        "Del": "Deneb Algedi",
        "Nu": "Alshat",
    },
    "Car": {
        "Alp": "Canopus",
        "Bet": "Miaplacidus",
        "Eps": "Avior",
        "Iot": "Aspidiske",
    },
    "Cas": {
        "Alp": "Schedar",
        "Bet": "Caph",
        "Gam": "Navi",
        "Del": "Ruchbah",
        "Eps": "Segin",
        "Zet": "Fulu",
        "Eta": "Achird",
        "Ups": "Castula",
    },
    "Cen": {
        "Alp": "Rigil Kentaurus",
        "Bet": "Hadar",
        "The": "Menkent",
    },
    "Cep": {
        "Alp": "Alderamin",
        "Bet": "Alfirk",
        "Gam": "Errai",
        "Xi": "Kurhah",
    },
    "Cet": {
        "Alp": "Menkar",
        "Bet": "Diphda",
        "Gam": "Kaffaljidhma",
        "Zet": "Baten Kaitos",
        "Omi": "Mira",
    },
    "Cha": {},
    "Cir": {},
    "Col": {
        "Alp": "Phact",
        "Bet": "Wazn",
        "The": "Elkurud",
    },
    "Com": {
        "Alp": "Diadem",
    },
    "CrA": {
        "Alp": "Meridiana",
    },
    "CrB": {
        "Alp": "Alphecca",
        "Bet": "Nusakan",
    },
    "Crv": {
        "Alp": "Alchiba",
        "Bet": "Kraz",
        "Gam": "Gienah",
        "Del": "Algorab",
        "Eps": "Minkar",
    },
    "Crt": {
        "Alp": "Alkes",
    },
    "Cru": {
        "Alp": "Acrux",
        "Bet": "Mimosa",
        "Gam": "Gacrux",
        "Del": "Imai",
        "Eps": "Ginan",
    },
    "Cyg": {
        "Alp": "Deneb",
        "Bet": "Albireo",
        "Gam": "Sadr",
        "Del": "Fawaris",
        "Eps": "Gienah",
        "Pi": "Azelfafage",
    },
    "Del": {
        "Alp": "Sualocin",
        "Bet": "Rotanev",
        "Eps": "Adulfin",
    },
    "Dor": {},
    "Dra": {
        "Alp": "Thuban",
        "Bet": "Rastaban",
        "Gam": "Eltanin",
        "Del": "Altais",
        "Zet": "Aldhibah",
        "Eta": "Athebyne",
        "Iot": "Edasich",
        "Lam": "Giausar",
        "Mu": "Alrakis",
        "Xi": "Grumium",
        "Phi": "Dziban",
    },
    "Equ": {
        "Alp": "Kitalpha",
    },
    "Eri": {
        "Alp": "Achernar",
        "Bet": "Cursa",
        "Gam": "Zaurak",
        "Eps": "Ran",
        "Zet": "Zibal",
        "Eta": "Azha",
        "The": "Acamar",
        "Omi": "Keid",
        "Tau": "Angetenar",
    },
    "For": {
        "Alp": "Dalim",
    },
    "Gem": {
        "Alp": "Castor",
        "Bet": "Pollux",
        "Gam": "Alhena",
        "Del": "Wasat",
        "Eps": "Mebsuta",
        "Zet": "Mekbuda",
        "Eta": "Propus",
        "Mu": "Tejat",
        "Xi": "Alzirr",
        "Omi": "Jishui",
    },
    "Gru": {
        "Alp": "Alnair",
        "Bet": "Tiaki",
        "Gam": "Aldhanab",
    },
    "Her": {
        "Alp": "Rasalgethi",
        "Bet": "Kornephoros",
        "Del": "Sarin",
        "Kap": "Marsic",
        "Lam": "Maasym",
        "Ome": "Cujam",
    },
    "Hor": {},
    "Hya": {
        "Alp": "Alphard",
        "Eps": "Ashlesha",
        "Iot": "Ukdah",
        "Sig": "Minchir",
        "Ups": "Zhang",
    },
    "Hyi": {},
    "Ind": {},
    "Lac": {},
    "Leo": {
        "Alp": "Regulus",
        "Bet": "Denebola",
        "Gam": "Algieba",
        "Del": "Zozma",
        "Eps": "Algenubi",
        "Zet": "Adhefera",
        "Eta": "Al Jabhah",
        "The": "Chertan",
        "Lam": "Alterf",
        "Mu": "Rasalas",
        "Omi": "Subra",
    },
    "LMi": {},
    "Lep": {
        "Alp": "Arneb",
        "Bet": "Nihal",
    },
    "Lib": {
        "Alp": "Zubenelgenubi",
        "Bet": "Zubeneschamali",
        "Gam": "Zubenelhakrabi",
        "Sig": "Brachium",
    },
    "Lup": {},
    "Lyn": {},
    "Lyr": {
        "Alp": "Vega",
        "Bet": "Sheliak",
        "Gam": "Sulafat",
        "Eta": "Aladfar",
    },
    "Men": {},
    "Mic": {},
    "Mon": {},
    "Mus": {},
    "Nor": {},
    "Oct": {
        "Sig": "Polaris Australis",
    },
    "Oph": {
        "Alp": "Rasalhague",
        "Bet": "Cebalrai",
        "Del": "Yed Prior",
        "Eps": "Yed Posterior",
        "Eta": "Sabik",
        "Lam": "Marfik",
    },
    "Ori": {
        "Alp": "Betelgeuse",
        "Bet": "Rigel",
        "Gam": "Bellatrix",
        "Del": "Mintaka",
        "Eps": "Alnilam",
        "Zet": "Alnitak",
        "Iot": "Hatysa",
        "Kap": "Saiph",
        "Lam": "Meissa",
    },
    "Pav": {
        "Alp": "Peacock",
    },
    "Peg": {
        "Alp": "Markab",
        "Bet": "Scheat",
        "Gam": "Algenib",
        "Del": "Alpheratz",
        "Eps": "Enif",
        "Zet": "Homam",
        "Eta": "Matar",
        "The": "Biham",
        "Mu": "Sadalbari",
        "Tau": "Salm",
        "Ups": "Alkarab",
    },
    "Per": {
        "Alp": "Mirfak",
        "Bet": "Algol",
        "Eta": "Miram",
        "Kap": "Misam",
        "Omi": "Atik",
        "Pi": "Gorgonea Secunda",
        "Rho": "Gorgonea Tertia",
        "Ome": "Gorgonea Quarta",
    },
    "Phe": {
        "Alp": "Ankaa",
        "Zet": "Wurren",
    },
    "Pic": {},
    "Psc": {
        "Alp": "Alrescha",
        "Bet": "Fumalsamakah",
        "Zet": "Revati",
        "Eta": "Alpherg",
        "Omi": "Torcular",
    },
    "PsA": {
        "Alp": "Fomalhaut",
    },
    "Pup": {
        "Zet": "Naos",
        "Xi": "Azmidi",
        "Rho": "Tureis",
    },
    "Pyx": {},
    "Ret": {},
    "Sge": {
        "Alp": "Sham",
    },
    "Sgr": {
        "Alp": "Rukbat",
        "Bet": "Arkab",
        "Gam": "Alnasl",
        "Del": "Kaus Media",
        "Eps": "Kaus Australis",
        "Zet": "Ascella",
        "Lam": "Kaus Borealis",
        "Mu": "Polis",
        "Nu": "Ainalrami",
        "Pi": "Albaldah",
        "Sig": "Nunki",
        "Ome": "Terebellum",
    },
    "Sco": {
        "Alp": "Antares",
        "Bet": "Acrab",
        "Del": "Dschubba",
        "Eps": "Larawag",
        "The": "Sargas",
        "Lam": "Shaula",
        "Mu": "Xamidimura",
        "Nu": "Jabbah",
        "Pi": "Fang",
        "Rho": "Iklil",
        "Sig": "Alniyat",
        "Tau": "Paikauhale",
        "Ups": "Lesath",
    },
    "Scl": {},
    "Sct": {},
    "Ser": {
        "Alp": "Unukalhai",
        "The": "Alya",
        "Kap": "Gudja",
    },
    "Sex": {},
    "Tau": {
        "Alp": "Aldebaran",
        "Bet": "Elnath",
        "Gam": "Prima Hyadum",
        "Del": "Secunda Hyadum",
        "Eps": "Ain",
        "Zet": "Tianguan",
        "Eta": "Alcyone",
        "The": "Chamukuy",
    },
    "Tel": {},
    "Tri": {
        "Alp": "Mothallah",
    },
    "TrA": {
        "Alp": "Atria",
        "Bet": "Betria",
        "Gam": "Gatria",
    },
    "Tuc": {},
    "UMa": {
        "Alp": "Dubhe",
        "Bet": "Merak",
        "Gam": "Phecda",
        "Del": "Megrez",
        "Eps": "Alioth",
        "Zet": "Mizar",
        "Eta": "Alkaid",
        "Iot": "Talitha",
        "Kap": "Alkaphrah",
        "Lam": "Tania Borealis",
        "Mu": "Tania Australis",
        "Nu": "Alula Borealis",
        "Xi": "Alula Australis",
        "Omi": "Muscida",
        "Chi": "Taiyangshou",
    },
    "UMi": {
        "Alp": "Polaris",
        "Bet": "Kochap",
        "Gam": "Pherkad",
        "Del": "Yildun",
    },
    "Vel": {
        "Gam": "Regor",
        "Del": "Alsephina",
        "Kap": "Markeb",
        "Lam": "Suhail",
    },
    "Vir": {
        "Alp": "Spica",
        "Bet": "Zavijava",
        "Gam": "Porrima",
        "Del": "Minelauva",
        "Eps": "Vindemiatrix",
        "Zet": "Heze",
        "Eta": "Zaniah",
        "Iot": "Syrma",
        "Kap": "Kang",
        "Phi": "Elgafar",
    },
    "Vol": {},
    "Vul": {
        "Alp": "Anser",
    },
}  # len=17
